[project]
name = "juan-marin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JuanFelipe", email = "juanfelipemarin906@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
juan-marin = "juan_marin:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
